### ISSUE TITLE
What should vctk_audio_text_train_filelist.txt be look like?

### ISSUE THREAD

**Issue by Charlottecuc** [facebookresearch/speech-resynthesis#5]
if we want to `train_f0_vq` on VTCK speakers

Thanks

**Comment by adampolyak** [comment]
Similar to the format of the files here: https://github.com/facebookresearch/speech-resynthesis/tree/main/datasets/VCTK/cpc100

You can replace vctk_audio_text_train_filelist.txt with datasets/VCTK/cpc100/train.txt
