### ISSUE TITLE
For VQ-VAE coding at 800 bps,  the "small" and "medium" audio about 6000 hours were used for training?

### ISSUE THREAD

**Issue by xiaoli1996** [facebookresearch/speech-resynthesis#6]
In the paper, "The VQ-VAE model employs the HiFiGAN decoder trained on the LibriLight dataset to match the amount of data reported in [34]." How many hours of LibriLight were used in the training?

**Comment by xiaoli1996** [comment]
The final bitrate of VQ-VAE 800bps codecs is the sum of the pitch bitrate with the content bitrate？

**Comment by adampolyak** [comment]
1. The vqvae encoder was trained on 6K hours from libri-light, built from the small+medium sections of the audio.
2. The final bitrate of the vqvae+f0 is 865. 800bps for vqvae and 65bps for the f0 stream.

**Comment by xiaoli1996** [comment]
> 1. The vqvae encoder was trained on 6K hours from libri-light, built from the small+medium sections of the audio.
> 2. The final bitrate of the vqvae+f0 is 865. 800bps for vqvae and 65bps for the f0 stream.

Thank you very much.

**Comment by xiaoli1996** [comment]
> 1. The vqvae encoder was trained on 6K hours from libri-light, built from the small+medium sections of the audio.
> 2. The final bitrate of the vqvae+f0 is 865. 800bps for vqvae and 65bps for the f0 stream.
In the MUSHRA subjective results of your paper, VQ-VAE 800bps does not include the  F0 encoder and speaker encoder?

**Comment by xiaoli1996** [comment]
> es, the vqvae model evaluated in our MUSHRA experiment is **without** F0 and speaker encoders.

Thank you again
