### ISSUE TITLE
Question about ./datasets/LibriLight/test.txt

### ISSUE THREAD

**Issue by xiaoli1996** [facebookresearch/speech-resynthesis#7]
In train.txt/val.txt/test.txt, what does “ 'cpc_km100': '-1' ” mean? Are there other available values for 'cpc_km100' apart from '-1'?

**Comment by adampolyak** [comment]
Unfortunately no.

We used LibriLight just for VQVAE training, therefore we didn't extract discrete codes for it for CPC or HuBERT.

**Comment by xiaoli1996** [comment]
Did you mean that: if I want to use LibriLight just for vqvae training, I must set 'cpc_km100':-1, 'hubert':-1 and 'vqvae256':-1 in the train.txt? or just set one of them?

**Comment by adampolyak** [comment]
use cpc_km100

**Comment by xiaoli1996** [comment]
Thank you very much!
