### ISSUE TITLE
How to use with cpu only?

### ISSUE THREAD

**Issue by DillFrescott** [facebookresearch/speech-resynthesis#9]
I only have an AMD GPU at the moment, so I cant use cuda. Is there a way to use cpu?

**Comment by adiyoss** [comment]
Hi @DillFrescott, 
Unfortunately, cuda is the only feasible option at the moment.
You can train it on cpu, but it will take the model forever to converge.

**Comment by DillFrescott** [comment]
Ok. Thank you for the info!
